apiVersion: batch/v1
kind: CronJob
metadata:
  name: ocp-ansible-healthcheck
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: ocp-ansible-healthcheck
    spec:
      template:
        spec:
          containers:
          - env:
            - name: USER
            - name: PASSWORD
            - name: URL
            image: HEALTHCHECK-IMAGE
            imagePullPolicy: Always
            name: ocp-ansible-healthcheck
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /tmp
              name: health
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          serviceAccount: ocp-ansible-healthcheck
          serviceAccountName: ocp-ansible-healthcheck
          terminationGracePeriodSeconds: 30
          volumes:
          - name: health
            persistentVolumeClaim:
              claimName: health
  schedule: 0 23 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
