---
 - name: List CSVs
   shell: oc get csv -A
   ignore_errors: true
   register: csv

 - name: List install plans not approved
   shell: oc get ip -A |sort -u | grep -v true$
   ignore_errors: true
   register: install_plan

 - name: Get installed Subscriptions
   shell: oc get subs -A
   ignore_errors: true
   register: subscriptions

 - name: Get installed Operators
   shell: oc get operators
   ignore_errors: true
   register: operators

 - name: Check CSVs without success
   shell: oc get csv -A | sort -u | grep -v Succeeded$
   ignore_errors: true
   register: csv_no_success

 - name: List install plans not approved
   shell: oc get ip -A |sort -u | grep -v true$
   ignore_errors: true
   register: install_plan_not_approved

 - set_fact:
     CSV_STATUS: "{{ csv.stdout }}"
     INSTALL_PLAN: "{{ install_plan.stdout }}"
     OPERATORS: "{{ operators.stdout }}"
     SUBSCRIPTIONS: "{{ subscriptions.stdout }}"
     CSV_NO_SUCCESS: "{{ csv_no_success.stdout }}"
     INSTALL_PLAN_NOT_APPROVED: "{{ install_plan_not_approved.stdout }}"

 - name: Create Report
   template:
     src: operators.j2
     dest: /tmp/report/report_operators.md
